# -*- coding: utf-8 -*-
"""sebastian_abeyta_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C1bwL99_Jl37wa7OJLeTDDikfqQ38U-T
"""



import streamlit as st
name = input("What is your name? ");
print("your name is", name);